# report.py — Generate a self-contained HTML summary report from the alerts log.

import html
import json
from datetime import datetime
from pathlib import Path


_SEVERITY_CLASS = {"HIGH": "high", "MEDIUM": "medium", "LOW": "low"}

# Double-brace {{ }} escapes literal braces inside str.format() templates.
_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Packet Analyzer Report — {date}</title>
<style>
  *    {{ box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117;
          color: #c9d1d9; margin: 0; padding: 24px 32px; }}
  h1   {{ color: #58a6ff; border-bottom: 1px solid #21262d; padding-bottom: 10px; }}
  h2   {{ color: #79c0ff; margin-top: 36px; margin-bottom: 10px; }}
  a    {{ color: #58a6ff; }}

  /* Stat cards */
  .stats {{ display: flex; gap: 16px; flex-wrap: wrap; margin: 20px 0; }}
  .card  {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px;
            padding: 18px 24px; min-width: 150px; text-align: center; }}
  .card .num {{ font-size: 2rem; font-weight: 700; color: #58a6ff; }}
  .card .lbl {{ font-size: 0.8rem; color: #8b949e; margin-top: 4px; }}

  /* Breakdown chips */
  .chips     {{ display: flex; flex-wrap: wrap; gap: 10px; margin-top: 8px; }}
  .chip      {{ background: #161b22; border: 1px solid #30363d; border-radius: 20px;
                padding: 4px 14px; font-size: 0.85rem; }}

  /* Alerts table */
  table  {{ width: 100%; border-collapse: collapse; margin-top: 10px;
            font-size: 0.875rem; }}
  th     {{ background: #161b22; color: #79c0ff; text-align: left;
            padding: 10px 12px; border-bottom: 2px solid #21262d; }}
  td     {{ padding: 8px 12px; border-bottom: 1px solid #21262d; }}
  tr:hover td {{ background: #161b22; }}

  /* Severity badges */
  .badge        {{ display: inline-block; border-radius: 12px; padding: 2px 10px;
                   font-size: 0.75rem; font-weight: 700; }}
  .badge.high   {{ background: #6e1010; color: #ffa0a0; border: 1px solid #ad2626; }}
  .badge.medium {{ background: #6b3600; color: #ffc97a; border: 1px solid #a55200; }}
  .badge.low    {{ background: #0f3d0f; color: #7ee787; border: 1px solid #1a6d1a; }}

  footer {{ margin-top: 48px; color: #484f58; font-size: 0.78rem; }}
</style>
</head>
<body>

<h1>&#x1f6e1;&#xfe0f; Packet Analyzer &amp; Anomaly Detector</h1>
<p style="color:#8b949e">Report generated: {date}</p>

<h2>Session Summary</h2>
<div class="stats">
  <div class="card"><div class="num">{total_packets}</div><div class="lbl">Packets (session)</div></div>
  <div class="card"><div class="num">{total_alerts}</div><div class="lbl">Total Alerts</div></div>
  <div class="card"><div class="num">{unique_ips}</div><div class="lbl">Unique Source IPs</div></div>
</div>

<h2>Alert Breakdown</h2>
<div class="chips">
{breakdown_chips}
</div>

<h2>All Alerts</h2>
<table>
<thead>
<tr>
  <th>Timestamp</th>
  <th>Type</th>
  <th>Severity</th>
  <th>Source IP</th>
  <th>Detail</th>
  <th>Pkts</th>
</tr>
</thead>
<tbody>
{alert_rows}
</tbody>
</table>

<h2>Source IP Summary</h2>
{ip_table}

<footer>
  Generated by Packet Analyzer &amp; Anomaly Detector &mdash; for authorized use on networks you own or have explicit permission to monitor.
</footer>
</body>
</html>
"""


def _load_alerts(alerts_file: str) -> list[dict]:
    """Read a JSONL alerts file and return a list of alert dicts."""
    alerts: list[dict] = []
    try:
        with open(alerts_file, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        alerts.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
    except FileNotFoundError:
        pass
    return alerts


def generate_html_report(alerts_file: str, output_file: str, stats: dict) -> None:
    """
    Read `alerts_file` (JSONL) and write a styled HTML report to `output_file`.
    `stats` is the runtime summary dict from main.py (packets, alerts, by_type).
    """
    alerts   = _load_alerts(alerts_file)
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Per-type counts
    type_counts: dict[str, int] = {}
    for a in alerts:
        t = a.get("alert_type", "UNKNOWN")
        type_counts[t] = type_counts.get(t, 0) + 1

    breakdown_chips = "\n".join(
        f'  <div class="chip"><strong>{html.escape(t)}</strong> &nbsp; {c}</div>'
        for t, c in sorted(type_counts.items())
    ) or '  <div class="chip">No alerts recorded.</div>'

    # Build table rows
    rows: list[str] = []
    for a in alerts:
        sev   = a.get("severity", "")
        cls   = _SEVERITY_CLASS.get(sev, "low")
        badge = f'<span class="badge {cls}">{html.escape(sev)}</span>'
        geo   = f" &nbsp;<span style='color:#8b949e;font-size:0.8em'>{html.escape(a['geo'])}</span>" if "geo" in a else ""
        rows.append(
            f"<tr>"
            f"<td>{html.escape(a.get('timestamp',''))}</td>"
            f"<td>{html.escape(a.get('alert_type',''))}</td>"
            f"<td>{badge}</td>"
            f"<td>{html.escape(a.get('source_ip',''))}{geo}</td>"
            f"<td>{html.escape(a.get('detail',''))}</td>"
            f"<td>{a.get('packets_involved','')}</td>"
            f"</tr>"
        )

    alert_rows = "\n".join(rows) if rows else (
        '<tr><td colspan="6" style="text-align:center;color:#484f58;padding:24px">'
        'No alerts recorded.</td></tr>'
    )

    unique_ips = len({a.get("source_ip") for a in alerts if a.get("source_ip")})

    # Build IP summary table from stats["ip_counts"] (populated by --show-ips)
    ip_counts = stats.get("ip_counts", {})
    if ip_counts:
        ip_rows_list: list[str] = []
        for ip, data in sorted(ip_counts.items(), key=lambda x: x[1]["count"], reverse=True):
            protos  = ", ".join(sorted(data["protocols"]))
            geo_str = data.get("geo", "")
            if "  |  ISP: " in geo_str:
                location, isp = geo_str.split("  |  ISP: ", 1)
            else:
                location, isp = geo_str, ""
            loc_cell = html.escape(location) if location else '<span style="color:#484f58">private / reserved</span>'
            isp_cell = html.escape(isp)       if isp      else '<span style="color:#484f58">—</span>'
            ip_rows_list.append(
                f"<tr>"
                f"<td>{html.escape(ip)}</td>"
                f"<td>{html.escape(protos)}</td>"
                f"<td>{data['count']:,}</td>"
                f"<td>{loc_cell}</td>"
                f"<td>{isp_cell}</td>"
                f"</tr>"
            )
        ip_table = (
            "<table>\n<thead>\n<tr>"
            "<th>Source IP</th><th>Protocols</th><th>Packets</th><th>Location</th><th>ISP</th>"
            "</tr>\n</thead>\n<tbody>\n"
            + "\n".join(ip_rows_list)
            + "\n</tbody>\n</table>"
        )
    else:
        ip_table = '<p style="color:#484f58;font-style:italic">No IP data — run with --show-ips to populate this section.</p>'

    html_out = _HTML.format(
        date            = date_str,
        total_packets   = f"{stats.get('packets', 0):,}",
        total_alerts    = f"{len(alerts):,}",
        unique_ips      = unique_ips,
        breakdown_chips = breakdown_chips,
        alert_rows      = alert_rows,
        ip_table        = ip_table,
    )

    Path(output_file).write_text(html_out, encoding="utf-8")
